version: '3.9'

services:
    # Service pour le serveur web
    nginx:
        image: nginx:1.22-alpine
        container_name: nginx
        ports:
            - 8008:80
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./:/code
        depends_on:
            - php
    php:
        build: .
        volumes:
            - ./:/code
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=host.docker.internal
            - DB_PORT=3306
            - DB_DATABASE=concours
            - DB_USERNAME=engelbert
            - DB_PASSWORD=root
        expose:
            - 9000
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - 8000:80
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=host.docker.internal
            - PMA_USER=engelbert
            - PMA_PASSWORD=root
        depends_on:
            - php
        
networks:
    default:
        driver: bridge