-- create Abonnement table
CREATE TABLE Abonnements (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    date_debut TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_fin TIMESTAMP NOT NULL,
    date_activation TIMESTAMP NOT NULL,
    codes_count INT NOT NULL DEFAULT 1,
    status ENUM('ACTIVE', 'INACTIVE') DEFAULT 'INACTIVE',
    user_id BIGINT NOT NULL,
    session_id BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES Users(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (session_id) REFERENCES Sessions(id) ON DELETE CASCADE ON UPDATE CASCADE
);
