-- Create Question table

CREATE TABLE Questions (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) ,
    description TEXT NOT NULL,
    photo_url VARCHAR(255),
    cours_id BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (cours_id) REFERENCES Cours(id) ON DELETE CASCADE ON UPDATE CASCADE
);
