-- Response table

CREATE TABLE Reponses(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) ,
    description TEXT NOT NULL,
    video_url VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    question_id BIGINT NOT NULL,
    FOREIGN KEY (question_id) REFERENCES Questions(id) ON DELETE CASCADE ON UPDATE CASCADE
);