-- create code tables
CREATE TABLE Codes(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    code VARCHAR(60) ,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    abonnement_id BIGINT NOT NULL,
    FOREIGN KEY (abonnement_id) REFERENCES Abonnements(id) ON DELETE CASCADE ON UPDATE CASCADE
);